export const TYPES = {
  CHART: {
    SET_CHART_DATA: "SET_CHART_DATA",
    BEGIN_GET_CHART_DATA: "BEGIN_GET_CHART_DATA",
    COMPLETE_GET_CHART_DATA: "COMPLETE_GET_CHART_DATA",
    CHANGE_CHART_DATA: "CHANGE_CHART_DATA",
  },
  MY_RECORD: {
    SET_MY_RECORD: "SET_MY_RECORD",
    BEGIN_GET_MY_RECORD: "BEGIN_GET_MY_RECORD",
    COMPLETE_GET_MY_RECORD: "COMPLETE_GET_MY_RECORD",
  },
  MY_MEALS: {
    SET_MY_MEALS_LIST: "SET_MY_MEALS_LIST",
    BEGIN_GET_MY_MEALS_LIST: "BEGIN_GET_MY_MEALS_LIST",
    COMPLETE_GET_MY_MEALS_LIST: "COMPLETE_GET_MY_MEALS_LIST",
    LOAD_MORE_MEALS: "LOAD_MORE_MEALS",
  },
  DIARY: {
    GET_DIARY_DATA: "GET_DIARY_DATA",
    LOAD_MORE_DIARY: "LOAD_MORE_DIARY",
  },
  COLUMNS: {
    GET_COLUMNS_DATA: "GET_COLUMNS_DATA",
    LOAD_MORE_COLUMNS: "LOAD_MORE_COLUMNS",
  },
};
